# Generated by Django 3.1.3 on 2020-12-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_user_identificator', models.CharField(db_index=True, max_length=30)),
                ('like_post_creator', models.CharField(db_index=True, max_length=30)),
                ('like_post_identificator', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identificator', models.CharField(db_index=True, max_length=30)),
                ('song_identificator', models.CharField(db_index=True, max_length=30)),
            ],
        ),
    ]
